# Generated by Django 3.2 on 2021-06-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_buyer_buyer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_password',
            field=models.CharField(max_length=50),
        ),
    ]
