# Generated by Django 3.2 on 2021-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_alter_buyer_buyer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('p_a', models.CharField(max_length=50)),
                ('p_b', models.CharField(max_length=50)),
                ('p_c', models.CharField(max_length=50)),
                ('r_a', models.IntegerField()),
                ('r_b', models.IntegerField()),
                ('r_c', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
