# Generated by Django 3.2 on 2021-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_auto_20210613_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='p_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='p_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='p_c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='r_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='r_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='r_c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
