# Generated by Django 3.2 on 2021-05-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_details', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_model', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=50)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom1.seller')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
