# Generated by Django 3.2 on 2021-04-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_names', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=100)),
                ('product_details', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_model', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=50)),
                ('seller_id', models.IntegerField()),
            ],
        ),
    ]
