# Generated by Django 3.2 on 2021-06-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom1', '0002_seller_seller_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_password',
            field=models.CharField(max_length=50),
        ),
    ]
