# Generated by Django 3.2 on 2021-04-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom1', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
