# Generated by Django 3.2 on 2021-04-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom1', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_names',
            new_name='category_name',
        ),
    ]
