# Generated by Django 3.2 on 2021-04-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom1', '0004_rename_category_names_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
