# Generated by Django 3.2 on 2021-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom1', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
