# Generated by Django 3.2 on 2021-05-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom1', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
